apiVersion: apps/v1
kind: Deployment
metadata:
  name: adv-msa-service-orderdetails
  labels:
    app: adv-msa-service-orderdetails
spec:
  replicas: 2
  selector:
   matchLabels:
    app: adv-msa-service-orderdetails
  template: 
    metadata:
      labels:
        app: adv-msa-service-orderdetails
    spec:
      containers:
      - name: adv-msa-service-orderdetails
        image: mvarun96/adv-msa-service-orderdetails
        ports:
        - containerPort: 8084