apiVersion: apps/v1
kind: Deployment
metadata:
  name: adv-msa-service-user
  labels:
    app: adv-msa-service-user
spec:
  replicas: 2
  selector:
   matchLabels:
    app: adv-msa-service-user
  template: 
    metadata:
      labels:
        app: adv-msa-service-user
    spec:
      containers:
      - name: adv-msa-service-user
        image: mvarun96/adv-msa-service-user
        ports:
        - containerPort: 8081